[package]
name = "rust-app"
version = "0.2.0"
authors = ["yhql"]
edition = "2018"
autobins = false

[dependencies]
ledger-parser-combinators = { git = "https://github.com/obsidiansystems/ledger-parser-combinators", branch = "working-in-speculos"}
arrayvec = { version = "0.7.1", default-features = false }
blake2 = { version = "0.9.1", default-features = false }

[features]
speculos = ["nanos_sdk/speculos"]

[target.thumbv6m-none-eabi.dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" } 
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" } 

[target.thumbv6m-none-eabi.dev-dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git", features= [ "speculos" ] }

[dev-dependencies]
testmacro = { git = "https://github.com/yhql/testmacro"}

[target.x86_64-unknown-linux-gnu.dev-dependencies]
ledger-apdu = { git = "https://github.com/zondax/ledger-rs.git" }
speculos-api = { path = "speculos-api" }
tokio = { version = "1", features = ["full"] } # features = ["full"] }
tokio-retry = "0.3.0"
hyper = { version = "0.14.10", features = ["client", "http1", "http2", "tcp"] }
hex = "0.4.3"
log = "0.4.14"
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
futures = "0.3.16"

[[bin]]
name = "rust-app"
test = false

[[test]]
name = "integration"
test = false

#[target.thumbv6m-none-eabi.unstable]
#build-std = ["core"]


[patch."https://github.com/LedgerHQ/ledger-nanos-sdk.git".nanos_sdk]
git = "https://github.com/ObsidianSystems/ledger-nanos-sdk.git"
branch = "use-ambient-compiler-and-target"

[profile.dev]
# panic = "abort"

[profile.release]
# panic = "abort"
opt-level = 'z' 
lto = true

[profile.test]


[package.metadata.nanos]
curve = "secp256k1"
flags = "0"
icon = "crab.gif"
